export const ADMIN = 'ADMIN';

export enum AdminActionEnum {
    FETCH_DISPLAY_REPORTS = 'FETCH_DISPLAY_REPORTS',
    FETCH_DISPLAY_REPORTS_SUCCESS = 'FETCH_DISPLAY_REPORTS_SUCCESS',
    FETCH_DISPLAY_REPORTS_ERROR = 'FETCH_DISPLAY_REPORTS_ERROR',
}
