# type: ignore
"""Added DCM warning table

Revision ID: 0546762b9264
Revises: acab1bb70979
Create Date: 2020-09-29 03:49:46.762108

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "0546762b9264"
down_revision = "acab1bb70979"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dcm_warning",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("schedule_date", sa.DateTime(), nullable=False),
        sa.Column("end_date", sa.DateTime(), nullable=False),
        sa.Column("event_type", sa.String(length=30), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dcm_warning")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("dcm_warning")
    # ### end Alembic commands ###
