# type: ignore
"""utility models added

Revision ID: 05a66de7708f
Revises: a04aacb318a3
Create Date: 2020-05-14 15:14:57.098787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "05a66de7708f"
down_revision = "a04aacb318a3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "utilities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("authorization_uid", sa.String(length=255), nullable=False),
        sa.Column("meter_uid", sa.String(length=255), nullable=False),
        sa.Column("uid", sa.String(length=255), nullable=False),
        sa.Column("utility", sa.String(length=255), nullable=False),
        sa.Column("service_identifier", sa.String(length=255), nullable=False),
        sa.Column("bill_end_date", sa.DateTime(), nullable=False),
        sa.Column("bill_start_date", sa.DateTime(), nullable=False),
        sa.Column("bill_total_cost", sa.Float(), nullable=False),
        sa.Column("bill_total_kwh", sa.Float(), nullable=False),
        sa.Column("bill_total_unit", sa.String(length=255), nullable=True),
        sa.Column("bill_total_volume", sa.Float(), nullable=False),
        sa.Column("peak_demand", sa.Float(), nullable=True),
        sa.Column("peak_demand_cost", sa.Float(), nullable=True),
        sa.Column("on_peak_demand", sa.Float(), nullable=True),
        sa.Column("on_peak_cost", sa.Float(), nullable=True),
        sa.Column("off_peak_demand", sa.Float(), nullable=True),
        sa.Column("off_peak_cost", sa.Float(), nullable=True),
        sa.Column("raw_url", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_utilities")),
        sa.UniqueConstraint("uid", name=op.f("uq_utilities_uid")),
    )
    op.create_table(
        "line_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("cost", sa.Float(), nullable=False),
        sa.Column("start", sa.DateTime(), nullable=False),
        sa.Column("end", sa.DateTime(), nullable=False),
        sa.Column("unit", sa.String(length=255), nullable=False),
        sa.Column("volume", sa.Float(), nullable=False),
        sa.Column("rate", sa.Float(), nullable=False),
        sa.Column("utility_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["utility_id"],
            ["utilities.id"],
            name=op.f("fk_line_items_utility_id_utilities"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_line_items")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("line_items")
    op.drop_table("utilities")
    # ### end Alembic commands ###
