"""Made usage column nullable

Revision ID: 061498d66d82
Revises: 642acdb59418
Create Date: 2020-07-13 13:00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '061498d66d82'
down_revision = '642acdb59418'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bill_history', 'usage',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bill_history', 'usage',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
