"""Renamed device to asset

Revision ID: 08741c739620
Revises: 9e13937be3c6
Create Date: 2020-07-13 13:00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '08741c739620'
down_revision = '9e13937be3c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('asset', 'device_type_id', nullable=True, new_column_name='asset_type_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('asset', 'asset_type_id', nullable=True, new_column_name='device_type_id')
    # ### end Alembic commands ###
