# type: ignore
"""Adding energy consumption table

Revision ID: 09b52dc34c95
Revises: c039264a7e84
Create Date: 2020-09-19 18:54:41.356372

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "09b52dc34c95"
down_revision = "c039264a7e84"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "energy_consumption",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("month", sa.Integer(), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("building_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["building_id"],
            ["buildings.id"],
            name=op.f("fk_energy_consumption_building_id_buildings"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_energy_consumption")),
        sa.UniqueConstraint(
            "building_id",
            "year",
            "month",
            name=op.f("uq_energy_consumption_building_id"),
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("energy_consumption")
    # ### end Alembic commands ###
