"""Added building consumption forecasts

Revision ID: 1358490a3fe2
Revises: 1e56b910baf5
Create Date: 2021-01-14 15:08:36.163485

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "1358490a3fe2"
down_revision = "1e56b910baf5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "building_consumption_forecast",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("building_id", sa.Integer(), nullable=False),
        sa.Column("utc_generation_ts", sa.DateTime(), nullable=False),
        sa.Column("utc_forecast_ts", sa.DateTime(), nullable=False),
        sa.Column("avg_consumption_kw", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["building_id"],
            ["building.id"],
            name=op.f("fk_building_consumption_forecast_building_id_building"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_building_consumption_forecast")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("building_consumption_forecast")
    # ### end Alembic commands ###
