# type: ignore
"""added_equipments

Revision ID: 14977375afd7
Revises: b85fad7fe29c
Create Date: 2020-09-09 18:33:34.213802

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "14977375afd7"
down_revision = "b85fad7fe29c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "equipments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["device_id"], ["devices.id"], name=op.f("fk_equipments_device_id_devices")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_equipments")),
    )
    op.alter_column(
        "dispatches",
        "event_type",
        existing_type=postgresql.ENUM(
            "DEMAND_REPSONSE", "ICAP", "DCM", name="eventtypes"
        ),
        nullable=False,
    )
    op.add_column("points", sa.Column("equipment_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        op.f("fk_points_equipment_id_equipments"),
        "points",
        "equipments",
        ["equipment_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_points_equipment_id_equipments"), "points", type_="foreignkey"
    )
    op.drop_column("points", "equipment_id")
    op.alter_column(
        "dispatches",
        "event_type",
        existing_type=postgresql.ENUM(
            "DEMAND_REPSONSE", "ICAP", "DCM", name="eventtypes"
        ),
        nullable=True,
    )
    op.drop_table("equipments")
    # ### end Alembic commands ###
