"""Renamed equipment to device

Revision ID: 1a8e67494891
Revises: 9af55d26e817
Create Date: 2020-07-13 13:00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1a8e67494891'
down_revision = '9af55d26e817'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('equipment', 'device')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('device', 'equipment')
    # ### end Alembic commands ###
