# type: ignore
"""empty message

Revision ID: 1ca327207da8
Revises: c2fb894f3be8
Create Date: 2020-05-07 15:31:05.576993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1ca327207da8"
down_revision = "c2fb894f3be8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("history", sa.Column("mode", sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("history", "mode")
    # ### end Alembic commands ###
