"""Dispatch column timezone aware

Revision ID: 1d8fc3d88c9f
Revises: ab41bc2d93bd
Create Date: 2021-01-30 14:08:51.033034

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1d8fc3d88c9f'
down_revision = 'ab41bc2d93bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE dispatch ALTER COLUMN schedule_date TYPE TIMESTAMP WITH TIME ZONE USING schedule_date AT TIME ZONE 'UTC'")
    op.execute("ALTER TABLE dispatch ALTER COLUMN end_date TYPE TIMESTAMP WITH TIME ZONE USING end_date AT TIME ZONE 'UTC'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE history ALTER COLUMN schedule_date TYPE TIMESTAMP WITHOUT TIME ZONE")
    op.execute("ALTER TABLE history ALTER COLUMN end_date TYPE TIMESTAMP WITHOUT TIME ZONE")
    # ### end Alembic commands ###
