# type: ignore
"""dispatch table name updated

Revision ID: 1d9f88fa28bf
Revises: a9391ec177e2
Create Date: 2020-05-28 11:04:16.170482

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "1d9f88fa28bf"
down_revision = "a9391ec177e2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dispatches",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("schedule_date", sa.DateTime(), nullable=False),
        sa.Column(
            "mode",
            postgresql.ENUM("IDLE", "CHARGING", "DISCHARGING", name="dispatchmodes",),
            nullable=False,
        ),
        sa.Column("power_kw", sa.Float(), nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["device_id"], ["devices.id"], name=op.f("fk_dispatches_device_id_devices")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dispatches")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("dispatches")
    postgresql.ENUM(name="dispatchmodes").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
