"""Add unique constraint for path in Point table

Revision ID: 2101dab78797
Revises: c29c85bb831e
Create Date: 2021-02-09 17:10:20.264575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2101dab78797"
down_revision = "c29c85bb831e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f("uq_point_path"), "point", ["path"])
    op.drop_constraint("uq_point_asset_id", "point", type_="unique")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uq_point_asset_id", "point", ["asset_id", "path"])
    op.drop_constraint(op.f("uq_point_path"), "point", type_="unique")
    # ### end Alembic commands ###
