"""Column name rename

Revision ID: 2a561b7d5c75
Revises: 60c991c986f7
Create Date: 2020-07-13 13:00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a561b7d5c75'
down_revision = '60c991c986f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unit', sa.Column('symbol', sa.String(length=255), nullable=False))
    op.create_unique_constraint(op.f('uq_unit_symbol'), 'unit', ['symbol'])
    op.drop_constraint('uq_unit_name', 'unit', type_='unique')
    op.drop_column('unit', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unit', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.create_unique_constraint('uq_unit_name', 'unit', ['name'])
    op.drop_constraint(op.f('uq_unit_symbol'), 'unit', type_='unique')
    op.drop_column('unit', 'symbol')
    # ### end Alembic commands ###
