"""Remove weather_station table

Revision ID: 3534e2cf56ab
Revises: cee59c24ec08
Create Date: 2021-03-08 14:54:00.632765

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "3534e2cf56ab"
down_revision = "cee59c24ec08"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("weather_station")
    op.execute("DROP TYPE weatherstationtype")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "weather_station",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column("name", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column(
            "station_type",
            postgresql.ENUM("NOAA", "WEATHER_GOV", name="weatherstationtype"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "address", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.Column("latitude", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("longitude", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "timezone", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name="pk_weather_station"),
        sa.UniqueConstraint("name", name="uq_weather_station_name"),
        sa.UniqueConstraint(
            "station_type", "address", name="uq_weather_station_station_type"
        ),
    )
    # ### end Alembic commands ###
