"""Table for gas and steam bill amounts

Revision ID: 37365be4e607
Revises: c039264a7e84
Create Date: 2020-09-23 08:48:34.324183

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '37365be4e607'
down_revision = 'c039264a7e84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bill_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('from_dt', sa.Integer(), nullable=False),
    sa.Column('to_dt', sa.Integer(), nullable=False),
    sa.Column('bill_amount', sa.Integer(), nullable=False),
    sa.Column('usage', sa.Integer(), nullable=False),
    sa.Column('unit', postgresql.ENUM('Therms', 'MLBS', name='utilityunit'), nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], name=op.f('fk_bill_history_building_id_buildings')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bill_history'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bill_history')
    # ### end Alembic commands ###
