"""Removed mode column from dispatches table

Revision ID: 37e5642f963d
Revises: 67a48de52a60
Create Date: 2020-07-13 13:00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '37e5642f963d'
down_revision = '67a48de52a60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dispatches', 'mode')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dispatches', sa.Column('mode', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
