"""Move Portfolio Manager meter columns from Building to Point table

Revision ID: 3911bca0beb4
Revises: 998018c9fe89
Create Date: 2021-03-23 12:00:59.473749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3911bca0beb4"
down_revision = "998018c9fe89"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("building", "portfolio_manager_solar_meter")
    op.drop_column("building", "portfolio_manager_grid_meter")
    op.add_column(
        "point", sa.Column("portfolio_manager_meterid", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("point", "portfolio_manager_meterid")
    op.add_column(
        "building",
        sa.Column(
            "portfolio_manager_grid_meter",
            sa.INTEGER(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "building",
        sa.Column(
            "portfolio_manager_solar_meter",
            sa.INTEGER(),
            autoincrement=False,
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
