"""Made columns unique

Revision ID: 3a05f67a5fc7
Revises: 85cf33e575c9
Create Date: 2020-06-29 23:08:43.269074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a05f67a5fc7'
down_revision = '85cf33e575c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_devices_building_id'), 'devices', ['building_id', 'name'])
    op.drop_constraint('uq_devices_name', 'devices', type_='unique')
    op.create_unique_constraint(op.f('uq_points_device_id'), 'points', ['device_id', 'name'])
    op.drop_constraint('uq_points_name', 'points', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_points_name', 'points', ['name'])
    op.drop_constraint(op.f('uq_points_device_id'), 'points', type_='unique')
    op.create_unique_constraint('uq_devices_name', 'devices', ['name'])
    op.drop_constraint(op.f('uq_devices_building_id'), 'devices', type_='unique')
    # ### end Alembic commands ###
