# type: ignore
"""Points and dispatch table updated.

Revision ID: 418c83857883
Revises: 61fd0cd09dfe
Create Date: 2020-06-10 13:03:06.881153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "418c83857883"
down_revision = "61fd0cd09dfe"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("dispatches", sa.Column("point_id", sa.Integer(), nullable=True))
    op.drop_constraint(
        "fk_dispatches_device_id_devices", "dispatches", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_dispatches_point_id_points"),
        "dispatches",
        "points",
        ["point_id"],
        ["id"],
    )
    op.drop_column("dispatches", "device_id")
    op.add_column("points", sa.Column("current_value", sa.Float(), nullable=True))
    op.add_column(
        "points", sa.Column("point_type", sa.String(length=255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("points", "point_type")
    op.drop_column("points", "current_value")
    op.add_column(
        "dispatches",
        sa.Column("device_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(
        op.f("fk_dispatches_point_id_points"), "dispatches", type_="foreignkey"
    )
    op.create_foreign_key(
        "fk_dispatches_device_id_devices",
        "dispatches",
        "devices",
        ["device_id"],
        ["id"],
    )
    op.drop_column("dispatches", "point_id")
    # ### end Alembic commands ###
