"""Dispatch removed point_id column

Revision ID: 423694de397f
Revises: d5f215335a06
Create Date: 2021-01-31 10:20:46.264078

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '423694de397f'
down_revision = 'd5f215335a06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dispatch', 'point_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ##
    op.add_column('dispatch', sa.Column('point_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_dispatches_point_id_points', 'dispatch', 'point', ['point_id'], ['id'])
    # ### end Alembic commands ###
