# type: ignore
"""billing peak connected to a building

Revision ID: 4571435448bf
Revises: 9ba21be9d5ab
Create Date: 2020-08-05 14:14:42.060351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4571435448bf"
down_revision = "9ba21be9d5ab"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "billing_peak", sa.Column("building_id", sa.Integer(), nullable=False)
    )
    op.add_column("billing_peak", sa.Column("from_time", sa.Date(), nullable=False))
    op.add_column("billing_peak", sa.Column("to_time", sa.Date(), nullable=False))
    op.drop_constraint(
        "fk_billing_peak_billing_cycle_id_billing_cycle",
        "billing_peak",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_billing_peak_building_id_buildings"),
        "billing_peak",
        "buildings",
        ["building_id"],
        ["id"],
    )
    op.drop_column("billing_peak", "billing_cycle_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "billing_peak",
        sa.Column(
            "billing_cycle_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint(
        op.f("fk_billing_peak_building_id_buildings"),
        "billing_peak",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_billing_peak_billing_cycle_id_billing_cycle",
        "billing_peak",
        "billing_cycle",
        ["billing_cycle_id"],
        ["id"],
    )
    op.drop_column("billing_peak", "to_time")
    op.drop_column("billing_peak", "from_time")
    op.drop_column("billing_peak", "building_id")
    # ### end Alembic commands ###
