"""Added column to asset type

Revision ID: 490ecdae7a46
Revises: 1a8e67494891
Create Date: 2020-07-13 13:00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '490ecdae7a46'
down_revision = '1a8e67494891'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset_type', sa.Column('is_controller_accessible', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asset_type', 'is_controller_accessible')
    # ### end Alembic commands ###
