# type: ignore
"""end_date added in dispatches table

Revision ID: 4f478a37229f
Revises: d9d272509d6c
Create Date: 2020-07-14 17:08:37.597889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4f478a37229f"
down_revision = "d9d272509d6c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("dispatches", sa.Column("end_date", sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("dispatches", "end_date")
    # ### end Alembic commands ###
