"""Renamed table to singular name

Revision ID: 4fd2ace3bb49
Revises: 9eba668f8a68
Create Date: 2020-07-13 13:00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4fd2ace3bb49'
down_revision = '9eba668f8a68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('devices', 'device')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('device', 'devices')
    # ### end Alembic commands ###
