"""Added company relationship

Revision ID: 57f29ad15286
Revises: e09a60f6069b
Create Date: 2020-08-23 06:03:29.615882

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '57f29ad15286'
down_revision = 'e09a60f6069b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buildings', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_buildings_company_id_companies'), 'buildings', 'companies', ['company_id'], ['id'])
    op.add_column('users', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_users_company_id_companies'), 'users', 'companies', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_users_company_id_companies'), 'users', type_='foreignkey')
    op.drop_column('users', 'company_id')
    op.drop_constraint(op.f('fk_buildings_company_id_companies'), 'buildings', type_='foreignkey')
    op.drop_column('buildings', 'company_id')
    # ### end Alembic commands ###
