"""Change column data type

Revision ID: 5ad65a4aaab5
Revises: adf80af66b11
Create Date: 2020-10-01 07:38:11.102876

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.types import Date as Sqlalchemy_Date


# revision identifiers, used by Alembic.
revision = '5ad65a4aaab5'
down_revision = 'adf80af66b11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bill_history', sa.Column('bill_amount_cents', sa.Integer(), nullable=False))
    op.drop_column('bill_history', 'bill_amount')
    op.drop_column('bill_history', 'from_dt')
    op.add_column('bill_history', sa.Column('from_dt', Sqlalchemy_Date(), nullable=False))
    op.drop_column('bill_history', 'to_dt')
    op.add_column('bill_history', sa.Column('to_dt', Sqlalchemy_Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bill_history', sa.Column('bill_amount', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('bill_history', 'bill_amount_cents')
    op.drop_column('bill_history', 'from_dt')
    op.add_column('bill_history', sa.Column('from_dt', sa.Integer(), nullable=False))
    op.drop_column('bill_history', 'to_dt')
    op.add_column('bill_history', sa.Column('to_dt', sa.Integer(), nullable=False))
    # ### end Alembic commands ###
