"""Added utility table

Revision ID: 608580925305
Revises: 73d07db61d39
Create Date: 2020-07-03 19:18:58.947271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '608580925305'
down_revision = '73d07db61d39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "utility",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),

        sa.PrimaryKeyConstraint("id", name=op.f("pk_utility")),
        sa.UniqueConstraint("name", name=op.f("uq_name")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("utility")
    # ### end Alembic commands ###
