# type: ignore
"""Updates power_kw field to Nullable=True

Revision ID: 61fd0cd09dfe
Revises: e7606ffde770
Create Date: 2020-06-04 12:40:03.278463

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "61fd0cd09dfe"
down_revision = "e7606ffde770"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "dispatches",
        "power_kw",
        existing_type=postgresql.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    op.alter_column(
        "dispatches",
        "status",
        existing_type=postgresql.ENUM(
            "PENDING", "SUCCESS", "FAIL", name="dispatchstatus"
        ),
        nullable=True,
        existing_server_default=sa.text("'PENDING'::dispatchstatus"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "dispatches",
        "status",
        existing_type=postgresql.ENUM(
            "PENDING", "SUCCESS", "FAIL", name="dispatchstatus"
        ),
        nullable=False,
        existing_server_default=sa.text("'PENDING'::dispatchstatus"),
    )
    op.alter_column(
        "dispatches",
        "power_kw",
        existing_type=postgresql.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    # ### end Alembic commands ###
