# type: ignore
"""Changes to billing cycle (#367)

Revision ID: 68e8a20af380
Revises: 9ba21be9d5ab
Create Date: 2020-08-02 15:46:30.144708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "68e8a20af380"
down_revision = "9ba21be9d5ab"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "billing_cycle",
        sa.Column("from_day", sa.Integer(), nullable=False, server_default="1"),
    )
    op.drop_constraint("uq_billing_cycle_building_id", "billing_cycle", type_="unique")
    op.create_unique_constraint(
        op.f("uq_billing_cycle_building_id"),
        "billing_cycle",
        ["building_id", "from_day"],
    )
    op.drop_column("billing_cycle", "to_dt")
    op.drop_column("billing_cycle", "from_dt")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "billing_cycle",
        sa.Column(
            "from_dt",
            sa.DATE(),
            autoincrement=False,
            nullable=False,
            server_default=sa.func.current_timestamp(),
        ),
    )
    op.add_column(
        "billing_cycle",
        sa.Column(
            "to_dt",
            sa.DATE(),
            autoincrement=False,
            nullable=False,
            server_default=sa.func.current_timestamp(),
        ),
    )
    op.drop_constraint(
        op.f("uq_billing_cycle_building_id"), "billing_cycle", type_="unique"
    )
    op.create_unique_constraint(
        "uq_billing_cycle_building_id",
        "billing_cycle",
        ["building_id", "from_dt", "to_dt"],
    )
    op.drop_column("billing_cycle", "from_day")
    # ### end Alembic commands ###
