"""Renamed to asset_id

Revision ID: 6d3936bea244
Revises: e3455f8b7b94
Create Date: 2020-07-13 13:00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6d3936bea244'
down_revision = 'e3455f8b7b94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('solar_edge_credential', 'device_id', nullable=False, new_column_name='asset_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('solar_edge_credential', 'asset_id', nullable=False, new_column_name='device_id')
    # ### end Alembic commands ###
