"""Drop EnergyStar.date

Revision ID: 6f4fcac2c71e
Revises: da12c5cfbf5c
Create Date: 2021-03-24 15:02:42.742181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6f4fcac2c71e"
down_revision = "da12c5cfbf5c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_energy_stars_building_id", "energy_stars", type_="unique")
    op.drop_column("energy_stars", "date")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "energy_stars",
        sa.Column("date", sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    )
    op.execute(
        "UPDATE energy_stars SET date=CONCAT_WS('/', lpad(month::text, 2, '0'), year::text);"
    )
    op.alter_column(
        "energy_stars", "date", existing_type=sa.VARCHAR(length=10), nullable=False
    )
    op.create_unique_constraint(
        "uq_energy_stars_building_id", "energy_stars", ["building_id", "date"]
    )
    # ### end Alembic commands ###
