"""Added utility_id to device

Revision ID: 6fe5b3de3f21
Revises: 608580925305
Create Date: 2020-07-03 20:16:26.694793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fe5b3de3f21'
down_revision = '608580925305'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('utility_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_devices_utility_id_utility'), 'devices', 'utility', ['utility_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_devices_utility_id_utility'), 'devices', type_='foreignkey')
    op.drop_column('devices', 'utility_id')
    # ### end Alembic commands ###
