"""Added point name column

Revision ID: 73c67a2a261b
Revises: bf57e5ddcb38
Create Date: 2020-06-30 08:04:06.776219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73c67a2a261b'
down_revision = 'bf57e5ddcb38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('points', sa.Column('name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('points', 'name')
    # ### end Alembic commands ###
