"""Added TZ and constraints to weather station table

Revision ID: 73f5bd652fe9
Revises: cf919f3e6d21
Create Date: 2021-01-14 12:04:41.837328

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "73f5bd652fe9"
down_revision = "cf919f3e6d21"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "weather_station", sa.Column("timezone", sa.String(length=255), nullable=False)
    )
    op.create_unique_constraint(
        op.f("uq_weather_station_name"), "weather_station", ["name"]
    )
    op.create_unique_constraint(
        op.f("uq_weather_station_station_type"),
        "weather_station",
        ["station_type", "address"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("uq_weather_station_station_type"), "weather_station", type_="unique"
    )
    op.drop_constraint(
        op.f("uq_weather_station_name"), "weather_station", type_="unique"
    )
    op.drop_column("weather_station", "timezone")
    # ### end Alembic commands ###
