"""Renamed device_type to asset_type

Revision ID: 7f238787ebfd
Revises: 08741c739620
Create Date: 2020-07-13 13:00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7f238787ebfd'
down_revision = '08741c739620'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('device_type', 'asset_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('asset_type', 'device_type')
    # ### end Alembic commands ###
