# type: ignore
"""building fk added in utilities

Revision ID: 80ec1367dba2
Revises: 05a66de7708f
Create Date: 2020-05-19 18:32:47.069013

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "80ec1367dba2"
down_revision = "05a66de7708f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "line_items",
        "rate",
        existing_type=postgresql.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    op.alter_column(
        "line_items", "unit", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.alter_column(
        "line_items",
        "volume",
        existing_type=postgresql.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    op.add_column("utilities", sa.Column("building_id", sa.Integer(), nullable=False))
    op.create_foreign_key(
        op.f("fk_utilities_building_id_buildings"),
        "utilities",
        "buildings",
        ["building_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_utilities_building_id_buildings"), "utilities", type_="foreignkey"
    )
    op.drop_column("utilities", "building_id")
    op.alter_column(
        "line_items",
        "volume",
        existing_type=postgresql.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    op.alter_column(
        "line_items", "unit", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.alter_column(
        "line_items",
        "rate",
        existing_type=postgresql.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    # ### end Alembic commands ###
