"""Removed unit column from points table

Revision ID: 84f3de5e91d4
Revises: 37e5642f963d
Create Date: 2020-07-13 13:00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '84f3de5e91d4'
down_revision = '37e5642f963d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('points', 'unit')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('points', sa.Column('unit', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
