"""Added weather_station table

Revision ID: 85d115b7106f
Revises: 83d708d10bdf
Create Date: 2021-01-13 12:42:50.391035

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "85d115b7106f"
down_revision = "83d708d10bdf"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "weather_station",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "station_type",
            sa.Enum("NOAA", "WEATHER_GOV", name="weatherstationtype"),
            nullable=False,
        ),
        sa.Column("address", sa.String(length=255), nullable=False),
        sa.Column("latitude", sa.Integer(), nullable=False),
        sa.Column("longitude", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_weather_station")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("weather_station")
    op.execute("DROP TYPE weatherstationtype")
    # ### end Alembic commands ###
