"""Remove uniquene constraints

Revision ID: 87a7396bfaab
Revises: 061498d66d82
Create Date: 2020-07-13 13:00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '87a7396bfaab'
down_revision = '061498d66d82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_n4_credential_password', 'n4_credential', type_='unique')
    op.drop_constraint('uq_n4_credential_port', 'n4_credential', type_='unique')
    op.drop_constraint('uq_n4_credential_username', 'n4_credential', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_n4_credential_username', 'n4_credential', ['username'])
    op.create_unique_constraint('uq_n4_credential_port', 'n4_credential', ['port'])
    op.create_unique_constraint('uq_n4_credential_password', 'n4_credential', ['password'])
    # ### end Alembic commands ###
