"""Made utility_idnon nullable

Revision ID: 8a3a6fdaff60
Revises: 6fe5b3de3f21
Create Date: 2020-07-03 20:42:36.369335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a3a6fdaff60'
down_revision = '6fe5b3de3f21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('devices', 'utility_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('devices', 'utility_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
