"""Added weather history and forecast tables

Revision ID: 97a835511bb3
Revises: cf919f3e6d21
Create Date: 2021-01-14 11:33:49.518691

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "97a835511bb3"
down_revision = "cf919f3e6d21"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "weather_forecast",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("weather_station_id", sa.Integer(), nullable=False),
        sa.Column("utc_generation_ts", sa.DateTime(), nullable=False),
        sa.Column("utc_forecast_ts", sa.DateTime(), nullable=False),
        sa.Column("dry_temp_f", sa.Float(), nullable=False),
        sa.Column("humidity", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["weather_station_id"],
            ["weather_station.id"],
            name=op.f("fk_weather_forecast_weather_station_id_weather_station"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_weather_forecast")),
    )
    op.create_table(
        "weather_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("weather_station_id", sa.Integer(), nullable=False),
        sa.Column("utc_ts", sa.DateTime(), nullable=False),
        sa.Column("dry_temp_f", sa.Float(), nullable=False),
        sa.Column("humidity", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["weather_station_id"],
            ["weather_station.id"],
            name=op.f("fk_weather_history_weather_station_id_weather_station"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_weather_history")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("weather_history")
    op.drop_table("weather_forecast")
    # ### end Alembic commands ###
