"""Add portfolio manager columns to building table

Revision ID: 998018c9fe89
Revises: dfd6578dd3e6
Create Date: 2021-03-17 10:51:57.750658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "998018c9fe89"
down_revision = "dfd6578dd3e6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "building",
        sa.Column("portfolio_manager_grid_meter", sa.Integer(), nullable=True),
    )
    op.add_column(
        "building",
        sa.Column("portfolio_manager_propertyid", sa.Integer(), nullable=True),
    )
    op.add_column(
        "building",
        sa.Column("portfolio_manager_solar_meter", sa.Integer(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("building", "portfolio_manager_solar_meter")
    op.drop_column("building", "portfolio_manager_propertyid")
    op.drop_column("building", "portfolio_manager_grid_meter")
    # ### end Alembic commands ###
