"""Renamed equipment_id to device_id

Revision ID: 9af55d26e817
Revises: d1116cfc96aa
Create Date: 2020-07-13 13:00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9af55d26e817'
down_revision = 'd1116cfc96aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('point', 'equipment_id', nullable=True, new_column_name='device_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('point', 'device_id', nullable=True, new_column_name='equipment_id')
    # ### end Alembic commands ###
