"""Meter enum changed to Other

Revision ID: 9ba21be9d5ab
Revises: b664b063cece
Create Date: 2020-07-30 15:12:39.715329

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9ba21be9d5ab'
down_revision = 'b664b063cece'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("devices", "asset_type")
    postgresql.ENUM(name="assettype").drop(op.get_bind(), checkfirst=True)
    asset_types = postgresql.ENUM(
        "HVAC",
        "METER",
        "OTHER",
        "LIGHT",
        "SOLAR",
        "BATTERY",
        "ELEVATOR",
        name="assettypes",
        create_type=False,
    )
    asset_types.create(op.get_bind())
    op.add_column("devices", sa.Column("asset_type", asset_types, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("devices", "asset_type")
    postgresql.ENUM(name="assettypes").drop(op.get_bind(), checkfirst=True)
    asset_type = postgresql.ENUM(
        "HVAC",
        "METER",
        "LIGHT",
        "SOLAR",
        "BATTERY",
        "ELEVATOR",
        name="assettype",
        create_type=False,
    )
    asset_type.create(op.get_bind())
    op.add_column("devices", sa.Column("asset_type", asset_type, nullable=True))
    # ### end Alembic commands ###