"""Unit table, add measure_of column

Revision ID: 9d028ff1930a
Revises: 514a221c216d
Create Date: 2021-03-06 13:19:01.733845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d028ff1930a'
down_revision = '514a221c216d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unit', sa.Column('measure_of', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('unit', 'measure_of')
    # ### end Alembic commands ###
