"""Renamed device to asset

Revision ID: 9e13937be3c6
Revises: af4024a663f0
Create Date: 2020-07-13 13:00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9e13937be3c6'
down_revision = 'af4024a663f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_asset_building_id'), 'asset', ['building_id', 'name'])
    op.create_unique_constraint(op.f('uq_point_asset_id'), 'point', ['asset_id', 'path'])
    op.drop_constraint('uq_points_device_id', 'point', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_points_device_id', 'point', ['asset_id', 'path'])
    op.drop_constraint(op.f('uq_point_asset_id'), 'point', type_='unique')
    op.drop_constraint(op.f('uq_asset_building_id'), 'asset', type_='unique')
    # ### end Alembic commands ###
