"""Renamed table to singular name

Revision ID: 9eba668f8a68
Revises: 1af6f12d81eb
Create Date: 2020-07-13 13:00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9eba668f8a68'
down_revision = '1af6f12d81eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('points', 'point')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('point', 'points')
    # ### end Alembic commands ###
