# type: ignore
"""energy_type added in device

Revision ID: a04aacb318a3
Revises: 18b57af41c8c
Create Date: 2020-05-13 14:23:42.403611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a04aacb318a3"
down_revision = "18b57af41c8c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "devices", sa.Column("energy_type", sa.String(length=255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("devices", "energy_type")
    # ### end Alembic commands ###
