# type: ignore
"""remove unit

Revision ID: a0a28d92daac
Revises: 80ec1367dba2
Create Date: 2020-05-21 12:55:57.779689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a0a28d92daac"
down_revision = "80ec1367dba2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("history", "unit")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "history",
        sa.Column("unit", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
