"""Create dnv_forecast table

Revision ID: a18f4e9a8cf7
Revises: 6f4fcac2c71e
Create Date: 2021-03-25 22:04:20.601807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a18f4e9a8cf7'
down_revision = '6f4fcac2c71e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dnv_forecast',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time_forecasted', sa.DateTime(), nullable=True),
    sa.Column('time_of_forecast', sa.DateTime(), nullable=True),
    sa.Column('power', sa.Integer(), nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['building.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dnv_forecast')
    # ### end Alembic commands ###
