# type: ignore
"""billing_account added in utility

Revision ID: a9391ec177e2
Revises: a0a28d92daac
Create Date: 2020-05-22 18:20:31.059233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a9391ec177e2"
down_revision = "a0a28d92daac"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "utilities", sa.Column("billing_account", sa.String(length=255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("utilities", "billing_account")
    # ### end Alembic commands ###
