"""History ts column timezone aware

Revision ID: ab41bc2d93bd
Revises: 75d3508666e9
Create Date: 2021-01-29 09:02:56.377035

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ab41bc2d93bd'
down_revision = '75d3508666e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE history ALTER COLUMN ts TYPE TIMESTAMP WITH TIME ZONE USING ts AT TIME ZONE 'UTC'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE history ALTER COLUMN ts TYPE TIMESTAMP WITHOUT TIME ZONE")
    # ### end Alembic commands ###
