"""Remove is_main from Point model

Revision ID: ab498d148208
Revises: 6ecc14b910d0
Create Date: 2021-02-25 13:14:27.525406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ab498d148208"
down_revision = "6ecc14b910d0"
branch_labels = None
depends_on = None


def upgrade():
    op.drop_column("point", "is_main")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "point",
        sa.Column(
            "is_main",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
