# type: ignore
"""Removing UtilityUnit enum

Revision ID: acab1bb70979
Revises: 16d17ba6229b
Create Date: 2020-09-29 01:21:09.616945

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "acab1bb70979"
down_revision = "16d17ba6229b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bill_history", "unit")
    postgresql.ENUM(name="utilityunit").drop(op.get_bind(), checkfirst=True)
    op.add_column(
        "bill_history",
        sa.Column("unit", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    )


# ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bill_history", "unit")
    utility_unit = postgresql.ENUM(
        "Therms", "MLBS", name="utilityunit", create_type=False
    )
    utility_unit.create(op.get_bind())
    op.add_column(
        "bill_history", sa.Column("unit", utility_unit, nullable=False,),
    )


# ### end Alembic commands ###
