"""Removed asset_type from point

Revision ID: ade04caf2018
Revises: 6c8e521ef612
Create Date: 2020-07-13 13:00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ade04caf2018'
down_revision = '6c8e521ef612'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('point', 'asset_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('point', sa.Column('asset_type', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
