"""Removed third_party column from devices

Revision ID: b0919bd36306
Revises: 84f3de5e91d4
Create Date: 2020-07-13 13:00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b0919bd36306'
down_revision = '84f3de5e91d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'third_party')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('third_party', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
