# type: ignore
"""point tags

Revision ID: b664b063cece
Revises: fc091f65faa7
Create Date: 2020-07-29 12:17:57.350120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b664b063cece"
down_revision = "fc091f65faa7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("points", sa.Column("tag", sa.String(length=255), nullable=True))
    op.alter_column(
        "points",
        "is_main",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("false"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "points",
        "is_main",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.drop_column("points", "tag")
    # ### end Alembic commands ###
