"""Added zipcode to building

Revision ID: b85fad7fe29c
Revises: f2bd31992375
Create Date: 2020-08-24 14:40:52.031250

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b85fad7fe29c'
down_revision = 'f2bd31992375'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buildings', sa.Column('zipcode', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('buildings', 'zipcode')
    # ### end Alembic commands ###
