# type: ignore
"""Changes per PR review

Revision ID: bd3e01887acb
Revises: 9ba21be9d5ab
Create Date: 2020-08-05 18:36:13.395891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "bd3e01887acb"
down_revision = "4571435448bf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "devices", sa.Column("third_party", sa.String(length=255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("devices", "third_party")
    # ### end Alembic commands ###
