"""Renamed points name to path

Revision ID: bf57e5ddcb38
Revises: 3a05f67a5fc7
Create Date: 2020-06-30 07:25:25.402779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf57e5ddcb38'
down_revision = '3a05f67a5fc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_points_device_id', 'points', type_='unique')
    op.alter_column('points', 'name', nullable=False, new_column_name='path')
    op.create_unique_constraint(op.f('uq_points_device_id'), 'points', ['device_id', 'path'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_points_device_id', 'points', type_='unique')
    op.alter_column('points', 'path', nullable=False, new_column_name='name')
    op.create_unique_constraint(op.f('uq_points_device_id'), 'points', ['device_id', 'name'])
    # ### end Alembic commands ###
