# type: ignore
"""added_energy_star

Revision ID: c039264a7e84
Revises: 4ff53c163d99
Create Date: 2020-09-14 20:15:58.885607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c039264a7e84"
down_revision = "4ff53c163d99"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "energy_stars",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("value", sa.Integer(), nullable=False),
        sa.Column("date", sa.String(length=10), nullable=False),
        sa.Column("building_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["building_id"],
            ["buildings.id"],
            name=op.f("fk_energy_stars_building_id_buildings"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_energy_stars")),
        sa.UniqueConstraint(
            "building_id", "date", name=op.f("uq_energy_stars_building_id")
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("energy_stars")
    # ### end Alembic commands ###
