# type: ignore
"""removed asset_type from Device model

Revision ID: c08ccadbec81
Revises: 6b003db71ab0
Create Date: 2020-08-06 21:55:25.263497

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "c08ccadbec81"
down_revision = "6b003db71ab0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("devices", "asset_type")
    postgresql.ENUM(name="assettypes").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    asset_types = postgresql.ENUM(
        "HVAC",
        "METER",
        "LIGHT",
        "SOLAR",
        "BATTERY",
        "ELEVATOR",
        name="assettypes",
        create_type=False,
    )
    asset_types.create(op.get_bind())
    op.add_column("devices", sa.Column("asset_type", asset_types, nullable=True))
    # ### end Alembic commands ###
