"""Rename gridX/Y -> gridx/y

Revision ID: c21006db3ad8
Revises: da63e3d9d960
Create Date: 2021-01-19 16:35:34.972391

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "c21006db3ad8"
down_revision = "da63e3d9d960"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "weather_gov_station_grid", sa.Column("gridx", sa.Integer(), nullable=False)
    )
    op.add_column(
        "weather_gov_station_grid", sa.Column("gridy", sa.Integer(), nullable=False)
    )
    op.drop_constraint(
        "uq_weather_gov_station_grid_weather_station_id",
        "weather_gov_station_grid",
        type_="unique",
    )
    op.create_unique_constraint(
        op.f("uq_weather_gov_station_grid_weather_station_id"),
        "weather_gov_station_grid",
        ["weather_station_id", "gridx", "gridy"],
    )
    op.drop_column("weather_gov_station_grid", "gridY")
    op.drop_column("weather_gov_station_grid", "gridX")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "weather_gov_station_grid",
        sa.Column("gridX", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "weather_gov_station_grid",
        sa.Column("gridY", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(
        op.f("uq_weather_gov_station_grid_weather_station_id"),
        "weather_gov_station_grid",
        type_="unique",
    )
    op.create_unique_constraint(
        "uq_weather_gov_station_grid_weather_station_id",
        "weather_gov_station_grid",
        ["weather_station_id", "gridX", "gridY"],
    )
    op.drop_column("weather_gov_station_grid", "gridy")
    op.drop_column("weather_gov_station_grid", "gridx")
    # ### end Alembic commands ###
