"""Deleted energy_demand and energy_consumption

Revision ID: c29c85bb831e
Revises: 423694de397f
Create Date: 2021-02-06 22:53:12.746712

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c29c85bb831e'
down_revision = '423694de397f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('history_copy')
    op.drop_table('energy_consumption')
    op.drop_table('energy_demand')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('energy_demand',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('month', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('value', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('building_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['building.id'], name='fk_energy_demand_building_id_buildings'),
    sa.PrimaryKeyConstraint('id', name='pk_energy_demand'),
    sa.UniqueConstraint('building_id', 'year', 'month', name='uq_energy_demand_building_id')
    )
    op.create_table('energy_consumption',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('month', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('value', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('building_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['building.id'], name='fk_energy_consumption_building_id_buildings'),
    sa.PrimaryKeyConstraint('id', name='pk_energy_consumption'),
    sa.UniqueConstraint('building_id', 'year', 'month', name='uq_energy_consumption_building_id')
    )
    # ### end Alembic commands ###
