# type: ignore
"""empty message

Revision ID: c2fb894f3be8
Revises: 33d0b93fd652
Create Date: 2020-05-04 21:52:26.268961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c2fb894f3be8"
down_revision = "33d0b93fd652"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("buildings", sa.Column("user_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        op.f("fk_buildings_user_id_users"), "buildings", "users", ["user_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_buildings_user_id_users"), "buildings", type_="foreignkey"
    )
    op.drop_column("buildings", "user_id")
    # ### end Alembic commands ###
