# type: ignore
"""remove utilitiy table from db

Revision ID: c755e05ef03c
Revises: 7ebd2ef47e0f
Create Date: 2020-07-15 22:05:46.260458

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "c755e05ef03c"
down_revision = "7ebd2ef47e0f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_devices_utility_id_utility", "devices", type_="foreignkey")
    op.drop_column("devices", "utility_id")
    op.drop_constraint("uq_history_point_id", "history", type_="unique")
    op.alter_column(
        "points",
        "writable",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("false"),
    )
    op.drop_table("utility")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "points",
        "writable",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.create_unique_constraint("uq_history_point_id", "history", ["point_id", "ts"])
    op.add_column(
        "devices",
        sa.Column("utility_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        "fk_devices_utility_id_utility", "devices", "utility", ["utility_id"], ["id"]
    )
    op.create_table(
        "utility",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column("name", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_utility"),
        sa.UniqueConstraint("name", name="uq_name"),
    )
    # ### end Alembic commands ###
