"""Added unit id column to points

Revision ID: ca2ffbe1539b
Revises: 87a7396bfaab
Create Date: 2020-07-13 13:00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ca2ffbe1539b'
down_revision = '87a7396bfaab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('points', sa.Column('unit_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_points_unit_id_unit'), 'points', 'unit', ['unit_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_points_unit_id_unit'), 'points', type_='foreignkey')
    op.drop_column('points', 'unit_id')
    # ### end Alembic commands ###
