# type: ignore
"""unique constraint for ts and point

Revision ID: cb26cf7b43a4
Revises: 6e8dc6b67e2a
Create Date: 2020-08-07 11:03:07.218569

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = "cb26cf7b43a4"
down_revision = "6e8dc6b67e2a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_history_point_id"), "history", ["point_id"], unique=False)
    op.create_unique_constraint(
        op.f("uq_history_point_id_ts"), "history", ["point_id", "ts"]
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_history_point_id"), table_name="history")
    op.drop_constraint(op.f("uq_history_point_id_ts"), "history", type_="unique")
    # ### end Alembic commands ###
