"""Remove weather_station_gov_grid table

Revision ID: cee59c24ec08
Revises: 784d61fc6f3b
Create Date: 2021-03-08 14:52:45.836613

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "cee59c24ec08"
down_revision = "784d61fc6f3b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("weather_gov_station_grid")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "weather_gov_station_grid",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "weather_station_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column("gridx", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("gridy", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["weather_station_id"],
            ["weather_station.id"],
            name="fk_weather_gov_station_grid_weather_station_id_weather_station",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_weather_gov_station_grid"),
        sa.UniqueConstraint(
            "weather_station_id",
            "gridx",
            "gridy",
            name="uq_weather_gov_station_grid_weather_station_id",
        ),
    )
    # ### end Alembic commands ###
