"""Add weather stations to building table

Revision ID: cf919f3e6d21
Revises: 85d115b7106f
Create Date: 2021-01-13 17:50:26.128166

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cf919f3e6d21'
down_revision = '85d115b7106f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('building', sa.Column('gov_weather_station_id', sa.Integer(), nullable=True))
    op.add_column('building', sa.Column('noaa_weather_station_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_building_gov_weather_station_id_weather_station'), 'building', 'weather_station', ['gov_weather_station_id'], ['id'])
    op.create_foreign_key(op.f('fk_building_noaa_weather_station_id_weather_station'), 'building', 'weather_station', ['noaa_weather_station_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_building_noaa_weather_station_id_weather_station'), 'building', type_='foreignkey')
    op.drop_constraint(op.f('fk_building_gov_weather_station_id_weather_station'), 'building', type_='foreignkey')
    op.drop_column('building', 'noaa_weather_station_id')
    op.drop_column('building', 'gov_weather_station_id')
    # ### end Alembic commands ###
