"""Renamed device_type to asset_type

Revision ID: d1116cfc96aa
Revises: 7f238787ebfd
Create Date: 2020-07-13 13:00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd1116cfc96aa'
down_revision = '7f238787ebfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_asset_type_name'), 'asset_type', ['name'])
    op.drop_constraint('uq_device_type_name', 'asset_type', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_device_type_name', 'asset_type', ['name'])
    op.drop_constraint(op.f('uq_asset_type_name'), 'asset_type', type_='unique')
    # ### end Alembic commands ###
