"""Dispatch with building_id column

Revision ID: d5f215335a06
Revises: 1d8fc3d88c9f
Create Date: 2021-01-31 09:04:26.721539

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd5f215335a06'
down_revision = '1d8fc3d88c9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dispatch', sa.Column('building_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_dispatch_building_id_building'), 'dispatch', 'building', ['building_id'], ['id'])
    op.drop_column('dispatch', 'asset_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_dispatch_building_id_building'), 'dispatch', type_='foreignkey')
    op.drop_column('dispatch', 'building_id')
    # ### end Alembic commands ###
