# type: ignore
"""event_types added in dispatches

Revision ID: d9d272509d6c
Revises: c755e05ef03c
Create Date: 2020-07-14 16:28:15.508119

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "d9d272509d6c"
down_revision = "c755e05ef03c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    event_types = postgresql.ENUM(
        "DemandResponse", "ICAP", name="eventtypes", create_type=False
    )
    event_types.create(op.get_bind())
    op.add_column(
        "dispatches", sa.Column("event_type", event_types, nullable=False,),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("dispatches", "event_type")
    postgresql.ENUM(name="eventtypes").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
