"""Added weather_gov_station_grid to building and weather_forecast tables

Revision ID: da63e3d9d960
Revises: f8c376bb6007
Create Date: 2021-01-19 14:15:36.571723

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "da63e3d9d960"
down_revision = "f8c376bb6007"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "building",
        sa.Column("weather_gov_station_grid_id", sa.Integer(), nullable=True),
    )
    op.drop_constraint(
        "fk_building_gov_weather_station_id_weather_station",
        "building",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_building_weather_gov_station_grid_id_weather_gov_station_grid"),
        "building",
        "weather_gov_station_grid",
        ["weather_gov_station_grid_id"],
        ["id"],
    )
    op.drop_column("building", "gov_weather_station_id")
    op.add_column(
        "weather_forecast",
        sa.Column("weather_gov_station_grid_id", sa.Integer(), nullable=True),
    )
    op.create_unique_constraint(
        op.f("uq_weather_forecast_weather_gov_station_grid_id"),
        "weather_forecast",
        ["weather_gov_station_grid_id", "utc_generation_ts", "utc_forecast_ts"],
    )
    op.drop_constraint(
        "fk_weather_forecast_weather_station_id_weather_station",
        "weather_forecast",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f(
            "fk_weather_forecast_weather_gov_station_grid_id_weather_gov_station_grid"
        ),
        "weather_forecast",
        "weather_gov_station_grid",
        ["weather_gov_station_grid_id"],
        ["id"],
    )
    op.drop_column("weather_forecast", "weather_station_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "weather_forecast",
        sa.Column(
            "weather_station_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint(
        op.f(
            "fk_weather_forecast_weather_gov_station_grid_id_weather_gov_station_grid"
        ),
        "weather_forecast",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_weather_forecast_weather_station_id_weather_station",
        "weather_forecast",
        "weather_station",
        ["weather_station_id"],
        ["id"],
    )
    op.drop_constraint(
        op.f("uq_weather_forecast_weather_gov_station_grid_id"),
        "weather_forecast",
        type_="unique",
    )
    op.drop_column("weather_forecast", "weather_gov_station_grid_id")
    op.add_column(
        "building",
        sa.Column(
            "gov_weather_station_id", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.drop_constraint(
        op.f("fk_building_weather_gov_station_grid_id_weather_gov_station_grid"),
        "building",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_building_gov_weather_station_id_weather_station",
        "building",
        "weather_station",
        ["gov_weather_station_id"],
        ["id"],
    )
    op.drop_column("building", "weather_gov_station_grid_id")
    # ### end Alembic commands ###
