"""Rename energy_stars -> energy_star, and energy_star.value -> energy_star.score

Revision ID: db6252bdd9d3
Revises: bb40827b9fa5
Create Date: 2021-03-26 11:59:18.044307

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "db6252bdd9d3"
down_revision = "bb40827b9fa5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("energy_stars", "energy_star")
    op.execute("ALTER SEQUENCE energy_stars_id_seq RENAME TO energy_star_id_seq")
    op.execute("ALTER INDEX pk_energy_stars RENAME TO pk_energy_star")
    op.execute(
        "ALTER INDEX energy_stars_building_id_month_year_key RENAME TO energy_star_building_id_month_year_key"
    )
    op.execute(
        "ALTER TABLE energy_star RENAME CONSTRAINT fk_energy_stars_building_id_buildings TO fk_energy_star_building_id_buildings"
    )
    op.alter_column("energy_star", "value", new_column_name="score")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("energy_star", "score", new_column_name="value")
    op.execute(
        "ALTER TABLE energy_star RENAME CONSTRAINT fk_energy_star_building_id_buildings TO fk_energy_stars_building_id_buildings"
    )
    op.execute(
        "ALTER INDEX energy_star_building_id_month_year_key RENAME TO energy_stars_building_id_month_year_key"
    )
    op.execute("ALTER INDEX pk_energy_star RENAME TO pk_energy_stars")
    op.execute("ALTER SEQUENCE energy_star_id_seq RENAME TO energy_stars_id_seq")
    op.rename_table("energy_star", "energy_stars")
    # ### end Alembic commands ###
