"""Billing tables

Revision ID: ddc6894c5051
Revises: 8a3a6fdaff60
Create Date: 2020-07-04 08:32:02.949156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddc6894c5051'
down_revision = '8a3a6fdaff60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_cycle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('from_dt', sa.Date(), nullable=False),
    sa.Column('to_dt', sa.Date(), nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], name=op.f('fk_billing_cycle_building_id_buildings')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_billing_cycle')),
    sa.UniqueConstraint('building_id', 'from_dt', 'to_dt', name=op.f('uq_billing_cycle_building_id'))
    )
    op.create_table('billing_peak',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('peak_value', sa.Float(), nullable=False),
    sa.Column('billing_cycle_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['billing_cycle_id'], ['billing_cycle.id'], name=op.f('fk_billing_peak_billing_cycle_id_billing_cycle')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_billing_peak'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('billing_peak')
    op.drop_table('billing_cycle')
    # ### end Alembic commands ###
