"""Added tz to building

Revision ID: de971390c478
Revises: c21006db3ad8
Create Date: 2021-01-21 20:56:22.513342

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'de971390c478'
down_revision = 'c21006db3ad8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('building', sa.Column('tz', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('building', 'tz')
    # ### end Alembic commands ###
