"""Building table, add column service_address

Revision ID: dfd6578dd3e6
Revises: 3534e2cf56ab
Create Date: 2021-03-11 09:50:24.676293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfd6578dd3e6'
down_revision = '3534e2cf56ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('building', sa.Column('service_address', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('building', 'service_address')
    # ### end Alembic commands ###
