"""Renamed table to singular name

Revision ID: e29db32fc7ce
Revises: e31f36de8dc0
Create Date: 2020-07-13 13:00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e29db32fc7ce'
down_revision = 'e31f36de8dc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_points_equipment_id_equipments', 'points', type_='foreignkey')
    op.rename_table('equipments', 'equipment')
    op.create_foreign_key(op.f('fk_points_equipment_id_equipment'), 'points', 'equipment', ['equipment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_points_equipment_id_equipment'), 'points', type_='foreignkey')
    op.rename_table('equipment', 'equipments')
    op.create_foreign_key('fk_points_equipment_id_equipments', 'points', 'equipments', ['equipment_id'], ['id'])
    # ### end Alembic commands ###
