"""Added device_type_id to devices table

Revision ID: e31f36de8dc0
Revises: 842769c19c90
Create Date: 2020-07-13 13:00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e31f36de8dc0'
down_revision = '842769c19c90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('device_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_devices_device_type_id_device_type'), 'devices', 'device_type', ['device_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_devices_device_type_id_device_type'), 'devices', type_='foreignkey')
    op.drop_column('devices', 'device_type_id')
    # ### end Alembic commands ###
