# type: ignore
"""remove current asset_type column

Revision ID: e3d217e57ce6
Revises: 4f478a37229f
Create Date: 2020-07-16 14:37:25.604033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e3d217e57ce6"
down_revision = "4f478a37229f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("devices", "asset_type")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "devices",
        sa.Column(
            "asset_type", sa.VARCHAR(length=60), autoincrement=False, nullable=True
        ),
    )
    # ### end Alembic commands ###
