"""Unit table, add measure_of column

Revision ID: e60364e4cc0f
Revises: 9d028ff1930a
Create Date: 2021-03-06 13:53:59.073053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e60364e4cc0f'
down_revision = '9d028ff1930a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('unit', 'measure_of',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('unit', 'measure_of',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
