# type: ignore
"""dispatch status added

Revision ID: e7606ffde770
Revises: 1d9f88fa28bf
Create Date: 2020-06-02 18:45:54.003887

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "e7606ffde770"
down_revision = "1d9f88fa28bf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    dispatch_status = postgresql.ENUM(
        "PENDING", "SUCCESS", "FAIL", name="dispatchstatus", create_type=False
    )
    dispatch_status.create(op.get_bind())
    op.add_column(
        "dispatches",
        sa.Column("status", dispatch_status, server_default="PENDING", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("dispatches", "status")
    postgresql.ENUM(name="dispatchstatus").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
