"""Added weather_gov_station_grid table

Revision ID: f8c376bb6007
Revises: 1358490a3fe2
Create Date: 2021-01-19 14:04:05.430452

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "f8c376bb6007"
down_revision = "1358490a3fe2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "weather_gov_station_grid",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("weather_station_id", sa.Integer(), nullable=False),
        sa.Column("gridX", sa.Integer(), nullable=False),
        sa.Column("gridY", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["weather_station_id"],
            ["weather_station.id"],
            name=op.f("fk_weather_gov_station_grid_weather_station_id_weather_station"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_weather_gov_station_grid")),
        sa.UniqueConstraint(
            "weather_station_id",
            "gridX",
            "gridY",
            name=op.f("uq_weather_gov_station_grid_weather_station_id"),
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("weather_gov_station_grid")
    # ### end Alembic commands ###
