# type: ignore
"""empty message

Revision ID: fc091f65faa7
Revises: 96d967870e48
Create Date: 2020-07-23 18:47:08.943589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "fc091f65faa7"
down_revision = "96d967870e48"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "points",
        sa.Column("is_main", sa.Boolean(), nullable=False, server_default="0"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("points", "is_main")
    # ### end Alembic commands ###
